import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations extends ChangeNotifier {
  AppLocalizations(this._locale) {
    _strings = _localizedValues[_locale.languageCode] ?? _localizedValues['en']!;
  }

  static const supportedLocales = [Locale('en'), Locale('ar')];
  static const _prefKey = 'locale';

  Locale _locale;
  late Map<String, String> _strings;

  Locale get locale => _locale;
  Map<String, String> get strings => _strings;
  String t(String key) => _strings[key] ?? key;

  static const _localizedValues = {
    'en': {
      'rooms': 'My Rooms',
      'devices': 'My Devices',
      'energy_consumption': 'Energy Consumption',
      'search_device': 'Search Device',
      'add_device': 'Add Device',
      'add_room': 'Add Room',
      'energy_analysis': 'Energy Analysis',
      'nav_home': 'Home',
      'nav_devices': 'Devices',
      'nav_rooms': 'Rooms',
      'nav_more': 'More',
      'greeting': 'Hello, {name}',
      'greeting_subtitle': 'Set up devices. Take control.',
      'onboarding_title_1': 'Effortless Control',
      'onboarding_title_2': 'Stay Informed Anywhere',
      'onboarding_title_3': 'Automate Comfort',
      'onboarding_desc_1': 'Manage every smart device in one elegant dashboard designed for speed.',
      'onboarding_desc_2': 'Monitor rooms, cameras, and energy trends no matter where you are.',
      'onboarding_desc_3': 'Create schedules and modes that keep your family comfortable automatically.',
      'next': 'Next',
      'skip': 'Skip',
      'get_started': 'Get Started',
      'sign_in_title': 'Welcome Back',
      'sign_up_title': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'sign_in_action': 'Sign In',
      'sign_up_action': 'Sign Up',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'create_now': 'Create one',
      'login_now': 'Log in',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'forgot_password_hint': 'Enter the email associated with your account and we\'ll send reset instructions.',
      'send_reset': 'Send reset link',
      'auth_error_invalid': 'Incorrect email or password.',
      'auth_error_exists': 'An account with this email already exists.',
      'auth_error_passwords': 'Passwords do not match.',
      'auth_error_weak_password': 'Password must be at least 6 characters.',
      'reset_email_sent': 'Reset email sent! Check your inbox.',
      'reset_email_sent_snack': 'Password reset instructions are on the way.',
      'reset_email_missing': 'We could not find an account with that email.',
      'terms_consent': 'I agree to the smart home terms of use and privacy policy.',
      'terms_required': 'Please accept the terms to continue.',
      'password_strong': 'Strong password',
      'password_good': 'Good password',
      'password_fair': 'Fair password',
      'password_weak': 'Weak password',
      'theme': 'Theme',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'language': 'Language',
      'choose_language': 'Choose language',
      'logout': 'Sign Out',
      'more_title': 'Profile & Settings',
      'user_access': 'User Access',
      'open': 'Open',
      'add_device_catalog': 'Browse catalog',
      'select_room': 'Select Room',
      'catalog_header': 'Smart Device Catalog',
      'catalog_subtitle': 'Pick a device to add to your home',
      'cancel': 'Cancel',
      'save': 'Save',
      'name_required': 'Name is required',
      'email_required': 'Email is required',
      'password_required': 'Password is required',
      'email_invalid': 'Please enter a valid email address',
      'welcome_back': 'Welcome back',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'device_added': '{name} added successfully',
      'enhancements_title': 'Automation & Safety Upgrades',
      'enhancements_description': 'Tailor advanced controls that level up your smart home.',
      'active_features': 'Active boosts',
      'no_active_features': 'Enable enhancements to highlight them here.',
      'view_guided_setup': 'Replay onboarding tour',
      'view_guided_setup_subtitle': 'Review tips and shortcuts from the initial walkthrough.',
      'guided_setup_title': 'Guided setup tips',
      'guided_setup_message': 'Here are the highlights from the onboarding experience.',
      'filter_all': 'All',
      'filter_online': 'Online',
      'filter_offline': 'Offline',
      'filter_favorites': 'Favorites',
      'status_on': 'On',
      'status_off': 'Off',
      'no_devices_found': 'No devices match your filters yet.',
      'device_health_ok': 'Optimal status',
      'device_health_idle': 'Standby',
      'scene_budget_guard_notice': 'Budget guard active — early alerts enabled.',
      'scene_away_summary': 'Away mode armed security and reduced power.',
      'scene_movie_summary': 'Lights dimmed and climate set for movie night.',
      'scene_wake_summary': 'Lights brightened and comfort restored for the morning.',
      'scene_clean_summary': 'Cleaning devices activated for a tidy home.',
      'scene_applied_generic': 'Scene applied.',
      'quick_scenes': 'Quick scenes',
      'scene_movie': 'Movie Night',
      'scene_away': 'Away Mode',
      'scene_wake': 'Good Morning',
      'scene_clean': 'Cleaning Cycle',
      'room_lock_applied': 'Security mode armed for this room.',
      'room_devices_on': 'Room devices activated.',
      'add_room_name_hint': 'Room name',
      'add_room_photo': 'Room photo',
      'add_room_devices_total': 'Total devices',
      'add_room_temperature_hint': 'Default temperature °C',
      'add_room_create': 'Create room',
      'room_added_success': 'Room added successfully.',
      'feature_vacation_mode_title': 'Vacation Mode',
      'feature_vacation_mode_subtitle': "Automate lighting, security, and energy use when you're away.",
      'feature_vacation_mode_chip': 'Vacation',
      'feature_night_lighting_title': 'Night Lighting Scene',
      'feature_night_lighting_subtitle': 'Dim pathways automatically at sunset for safe navigation.',
      'feature_night_lighting_chip': 'Night',
      'feature_energy_saver_title': 'Energy Saver',
      'feature_energy_saver_subtitle': 'Optimize device schedules to reduce standby consumption.',
      'feature_energy_saver_chip': 'Saver',
      'feature_auto_lock_title': 'Auto-Lock Doors',
      'feature_auto_lock_subtitle': 'Lock every connected door after a timeout or when everyone leaves.',
      'feature_auto_lock_chip': 'Auto lock',
      'feature_presence_simulation_title': 'Presence Simulation',
      'feature_presence_simulation_subtitle': 'Rotate lights and media to simulate someone at home.',
      'feature_presence_simulation_chip': 'Presence',
      'feature_air_quality_watch_title': 'Air Quality Watch',
      'feature_air_quality_watch_subtitle': 'Monitor temperature and humidity to recommend comfort tweaks.',
      'feature_air_quality_watch_chip': 'Air',
      'feature_pet_monitor_title': 'Pet Monitor',
      'feature_pet_monitor_subtitle': 'Track pet-friendly rooms and notify you when motion is detected.',
      'feature_pet_monitor_chip': 'Pets',
      'feature_leak_alerts_title': 'Leak Alerts',
      'feature_leak_alerts_subtitle': 'Watch water sensors and instantly notify the household.',
      'feature_leak_alerts_chip': 'Leak',
      'feature_device_health_title': 'Device Health',
      'feature_device_health_subtitle': 'Surface diagnostics when devices need attention.',
      'feature_device_health_chip': 'Health',
      'feature_battery_watch_title': 'Battery Watch',
      'feature_battery_watch_subtitle': 'Keep tabs on battery-powered gadgets with low power alerts.',
      'feature_battery_watch_chip': 'Battery',
      'feature_security_patrol_title': 'Security Patrol',
      'feature_security_patrol_subtitle': 'Schedule camera sweeps and audible deterrents overnight.',
      'feature_security_patrol_chip': 'Patrol',
      'feature_guest_pass_title': 'Guest Passes',
      'feature_guest_pass_subtitle': 'Issue temporary access codes for visitors with quick expiration.',
      'feature_guest_pass_chip': 'Guest',
      'feature_voice_assistant_title': 'Voice Assistant Link',
      'feature_voice_assistant_subtitle': 'Sync voice commands and quick phrases with your scenes.',
      'feature_voice_assistant_chip': 'Voice',
      'feature_geo_fencing_title': 'Geo-Fencing',
      'feature_geo_fencing_subtitle': 'Trigger automations when household members arrive or leave.',
      'feature_geo_fencing_chip': 'Geofence',
      'feature_cleaning_cycle_title': 'Cleaning Cycles',
      'feature_cleaning_cycle_subtitle': 'Coordinate vacuums and air purifiers for spotless rooms.',
      'feature_cleaning_cycle_chip': 'Clean',
      'feature_smart_notifications_title': 'Smart Notifications',
      'feature_smart_notifications_subtitle': 'Bundle alerts into meaningful digests at the right moment.',
      'feature_smart_notifications_chip': 'Smart alerts',
      'feature_routine_suggestions_title': 'Routine Suggestions',
      'feature_routine_suggestions_subtitle': 'Get AI-powered routine ideas based on device usage.',
      'feature_routine_suggestions_chip': 'Suggestions',
      'feature_peak_protection_title': 'Peak Protection',
      'feature_peak_protection_subtitle': 'Automatically throttle heavy devices during peak pricing.',
      'feature_peak_protection_chip': 'Peak',
      'feature_solar_sync_title': 'Solar Sync',
      'feature_solar_sync_subtitle': 'Balance energy loads with your solar production timeline.',
      'feature_solar_sync_chip': 'Solar',
      'feature_green_tips_title': 'Green Tips',
      'feature_green_tips_subtitle': 'Receive eco insights to keep consumption sustainable.',
      'feature_green_tips_chip': 'Green',
      'feature_insights_digest_title': 'Insights Digest',
      'feature_insights_digest_subtitle': 'Weekly summary with highlights across rooms and energy.',
      'feature_insights_digest_chip': 'Digest',
      'feature_scene_learning_title': 'Scene Learning',
      'feature_scene_learning_subtitle': 'Let the system learn and refine your manual adjustments.',
      'feature_scene_learning_chip': 'Learning',
      'feature_firmware_auto_title': 'Auto Firmware',
      'feature_firmware_auto_subtitle': 'Schedule firmware updates at night to keep devices secure.',
      'feature_firmware_auto_chip': 'Updates',
      'feature_backup_restore_title': 'Backup & Restore',
      'feature_backup_restore_subtitle': 'Safely backup layouts and restore with a tap.',
      'feature_backup_restore_chip': 'Backup',
      'feature_mfa_title': 'Two-Factor Login',
      'feature_mfa_subtitle': 'Add multi-factor approval for remote access.',
      'feature_mfa_chip': '2FA',
      'feature_privacy_mode_title': 'Privacy Mode',
      'feature_privacy_mode_subtitle': 'Disable microphones and cameras with one privacy switch.',
      'feature_privacy_mode_chip': 'Privacy',
      'feature_shared_alerts_title': 'Shared Alerts',
      'feature_shared_alerts_subtitle': 'Notify family members immediately when critical events happen.',
      'feature_shared_alerts_chip': 'Shared',
      'feature_automation_sandbox_title': 'Automation Sandbox',
      'feature_automation_sandbox_subtitle': 'Prototype advanced automations before rolling them out.',
      'feature_automation_sandbox_chip': 'Sandbox',
      'feature_energy_budget_guard_title': 'Energy Budget Guard',
      'feature_energy_budget_guard_subtitle': 'Set monthly budgets and receive alerts before overages.',
      'feature_energy_budget_guard_chip': 'Budget',
      'feature_maintenance_scheduler_title': 'Maintenance Scheduler',
      'feature_maintenance_scheduler_subtitle': 'Track filter changes and maintenance appointments.',
      'feature_maintenance_scheduler_chip': 'Maintenance',
    },
    'ar': {
      'rooms': 'غرفي',
      'devices': 'أجهزتي',
      'energy_consumption': 'استهلاك الطاقة',
      'search_device': 'ابحث عن جهاز',
      'add_device': 'أضف جهازًا',
      'add_room': 'أضف غرفة',
      'energy_analysis': 'تحليل الطاقة',
      'nav_home': 'الرئيسية',
      'nav_devices': 'الأجهزة',
      'nav_rooms': 'الغرف',
      'nav_more': 'المزيد',
      'greeting': 'مرحبًا، {name}',
      'greeting_subtitle': 'قم بضبط الأجهزة وتحكم فيها بسهولة.',
      'onboarding_title_1': 'تحكم بلا مجهود',
      'onboarding_title_2': 'ابقَ على اطلاع في أي مكان',
      'onboarding_title_3': 'راحة مؤتمتة',
      'onboarding_desc_1': 'أدر كل أجهزتك الذكية من لوحة واحدة أنيقة وسريعة.',
      'onboarding_desc_2': 'راقب الغرف والكاميرات واستهلاك الطاقة أينما كنت.',
      'onboarding_desc_3': 'أنشئ جداول وأوضاعًا تبقي عائلتك مرتاحة تلقائيًا.',
      'next': 'التالي',
      'skip': 'تخطي',
      'get_started': 'ابدأ الآن',
      'sign_in_title': 'مرحبًا بعودتك',
      'sign_up_title': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'full_name': 'الاسم الكامل',
      'sign_in_action': 'تسجيل الدخول',
      'sign_up_action': 'إنشاء حساب',
      'no_account': 'لا تملك حسابًا؟',
      'have_account': 'لديك حساب بالفعل؟',
      'create_now': 'أنشئ واحدًا',
      'login_now': 'سجّل الدخول',
      'remember_me': 'تذكرني',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'forgot_password_hint': 'أدخل البريد المرتبط بحسابك لنرسل تعليمات إعادة التعيين.',
      'send_reset': 'إرسال رابط الاستعادة',
      'auth_error_invalid': 'البريد أو كلمة المرور غير صحيحة.',
      'auth_error_exists': 'هناك حساب مسجل بهذا البريد الإلكتروني.',
      'auth_error_passwords': 'كلمتا المرور غير متطابقتين.',
      'auth_error_weak_password': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
      'reset_email_sent': 'تم إرسال بريد إعادة التعيين! راجع صندوقك.',
      'reset_email_sent_snack': 'تم إرسال تعليمات إعادة كلمة المرور.',
      'reset_email_missing': 'لم نجد حسابًا مرتبطًا بهذا البريد.',
      'terms_consent': 'أوافق على شروط الاستخدام وسياسة الخصوصية للمنزل الذكي.',
      'terms_required': 'يرجى الموافقة على الشروط للمتابعة.',
      'password_strong': 'كلمة مرور قوية',
      'password_good': 'كلمة مرور جيدة',
      'password_fair': 'كلمة مرور متوسطة',
      'password_weak': 'كلمة مرور ضعيفة',
      'theme': 'السمة',
      'theme_light': 'فاتحة',
      'theme_dark': 'داكنة',
      'theme_system': 'حسب النظام',
      'language': 'اللغة',
      'choose_language': 'اختر اللغة',
      'logout': 'تسجيل الخروج',
      'more_title': 'الملف والإعدادات',
      'user_access': 'صلاحيات المستخدم',
      'open': 'فتح',
      'add_device_catalog': 'تصفح الكتالوج',
      'select_room': 'اختر الغرفة',
      'catalog_header': 'كتالوج الأجهزة الذكية',
      'catalog_subtitle': 'اختر جهازًا لإضافته إلى منزلك',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'name_required': 'الاسم مطلوب',
      'email_required': 'البريد مطلوب',
      'password_required': 'كلمة المرور مطلوبة',
      'email_invalid': 'يرجى إدخال بريد إلكتروني صالح',
      'welcome_back': 'مرحبًا مجددًا',
      'sign_out_confirm': 'هل تريد تسجيل الخروج؟',
      'device_added': 'تمت إضافة {name} بنجاح',
      'enhancements_title': 'الأتمتة والحماية المتقدمة',
      'enhancements_description': 'خصص عناصر التحكم المتطورة لتعزيز منزلك الذكي.',
      'active_features': 'الميزات المفعلة',
      'no_active_features': 'فعّل التحسينات لعرضها هنا.',
      'view_guided_setup': 'إعادة جولة البدء',
      'view_guided_setup_subtitle': 'راجع النصائح والاختصارات من الجولة الأولى.',
      'guided_setup_title': 'نصائح الإعداد الإرشادي',
      'guided_setup_message': 'إليك أبرز النقاط من جولة البداية.',
      'filter_all': 'الكل',
      'filter_online': 'قيد التشغيل',
      'filter_offline': 'متوقف',
      'filter_favorites': 'المفضلة',
      'status_on': 'تشغيل',
      'status_off': 'إيقاف',
      'no_devices_found': 'لا توجد أجهزة مطابقة للمرشحات.',
      'device_health_ok': 'حالة مثالية',
      'device_health_idle': 'وضع الاستعداد',
      'scene_budget_guard_notice': 'تم تفعيل حارس الميزانية لتنبيهات مبكرة.',
      'scene_away_summary': 'وضع السفر فعّل الأمان وخفّض الاستهلاك.',
      'scene_movie_summary': 'تم تهيئة الإضاءة والمناخ لوقت السينما.',
      'scene_wake_summary': 'أعيدت الإضاءة والراحة لصباح نشط.',
      'scene_clean_summary': 'بدأت أجهزة التنظيف العمل لمنزل مرتب.',
      'scene_applied_generic': 'تم تطبيق المشهد.',
      'quick_scenes': 'مشاهد سريعة',
      'scene_movie': 'وضع السينما',
      'scene_away': 'وضع السفر',
      'scene_wake': 'صباح الخير',
      'scene_clean': 'دورة التنظيف',
      'room_lock_applied': 'تم تفعيل وضع الأمان لهذه الغرفة.',
      'room_devices_on': 'تم تشغيل أجهزة الغرفة.',
      'add_room_name_hint': 'اسم الغرفة',
      'add_room_photo': 'صورة الغرفة',
      'add_room_devices_total': 'إجمالي الأجهزة',
      'add_room_temperature_hint': 'درجة الحرارة الافتراضية °م',
      'add_room_create': 'إنشاء غرفة',
      'room_added_success': 'تمت إضافة الغرفة بنجاح.',
      'feature_vacation_mode_title': 'وضع السفر',
      'feature_vacation_mode_subtitle': 'أتمت الإضاءة والأمن والطاقة عند المغادرة.',
      'feature_vacation_mode_chip': 'سفر',
      'feature_night_lighting_title': 'إضاءة ليلية',
      'feature_night_lighting_subtitle': 'تعتيم الممرات تلقائيًا عند الغروب لمرور آمن.',
      'feature_night_lighting_chip': 'ليلي',
      'feature_energy_saver_title': 'موفر الطاقة',
      'feature_energy_saver_subtitle': 'اضبط الجداول لتقليل الاستهلاك أثناء الاستعداد.',
      'feature_energy_saver_chip': 'توفير',
      'feature_auto_lock_title': 'إقفال تلقائي',
      'feature_auto_lock_subtitle': 'أغلق الأبواب الذكية بعد مدة أو عند مغادرة الجميع.',
      'feature_auto_lock_chip': 'قفل',
      'feature_presence_simulation_title': 'محاكاة وجود',
      'feature_presence_simulation_subtitle': 'بدّل الأضواء والوسائط لتبدو وكأن المنزل مأهول.',
      'feature_presence_simulation_chip': 'وجود',
      'feature_air_quality_watch_title': 'مراقبة جودة الهواء',
      'feature_air_quality_watch_subtitle': 'راقب الحرارة والرطوبة واقترح تحسينات الراحة.',
      'feature_air_quality_watch_chip': 'هواء',
      'feature_pet_monitor_title': 'مراقب الحيوانات الأليفة',
      'feature_pet_monitor_subtitle': 'تعقب غرف الحيوانات ونبهك عند اكتشاف الحركة.',
      'feature_pet_monitor_chip': 'حيوانات',
      'feature_leak_alerts_title': 'تنبيهات التسرب',
      'feature_leak_alerts_subtitle': 'راقب حساسات المياه وبلغ الجميع فورًا.',
      'feature_leak_alerts_chip': 'تسرب',
      'feature_device_health_title': 'صحة الأجهزة',
      'feature_device_health_subtitle': 'اعرض التشخيص عند حاجتها للعناية.',
      'feature_device_health_chip': 'صحة',
      'feature_battery_watch_title': 'مراقب البطارية',
      'feature_battery_watch_subtitle': 'تابع الأجهزة بالبطاريات وتنبيهات انخفاض الطاقة.',
      'feature_battery_watch_chip': 'بطارية',
      'feature_security_patrol_title': 'دوريات أمنية',
      'feature_security_patrol_subtitle': 'جدول مسح الكاميرات ومنع المتطفلين ليلًا.',
      'feature_security_patrol_chip': 'دورية',
      'feature_guest_pass_title': 'تصاريح الضيوف',
      'feature_guest_pass_subtitle': 'أنشئ أكوادًا مؤقتة للزوار تنتهي سريعًا.',
      'feature_guest_pass_chip': 'ضيوف',
      'feature_voice_assistant_title': 'ربط المساعد الصوتي',
      'feature_voice_assistant_subtitle': 'زامن الأوامر الصوتية والمشاهد السريعة.',
      'feature_voice_assistant_chip': 'صوت',
      'feature_geo_fencing_title': 'سياج جغرافي',
      'feature_geo_fencing_subtitle': 'شغّل الأتمتة عند وصول أو مغادرة الأفراد.',
      'feature_geo_fencing_chip': 'جغرافيا',
      'feature_cleaning_cycle_title': 'دورات التنظيف',
      'feature_cleaning_cycle_subtitle': 'نسّق المكانس ومنقيات الهواء لتبقى الغرف نظيفة.',
      'feature_cleaning_cycle_chip': 'تنظيف',
      'feature_smart_notifications_title': 'تنبيهات ذكية',
      'feature_smart_notifications_subtitle': 'جمع التنبيهات في موجز مفيد بالوقت المناسب.',
      'feature_smart_notifications_chip': 'تنبيه ذكي',
      'feature_routine_suggestions_title': 'اقتراحات الروتين',
      'feature_routine_suggestions_subtitle': 'احصل على روتينات مقترحة بناءً على استخدامك.',
      'feature_routine_suggestions_chip': 'روتين',
      'feature_peak_protection_title': 'حماية الذروة',
      'feature_peak_protection_subtitle': 'خفّض الأجهزة الثقيلة وقت تعرفة الذروة.',
      'feature_peak_protection_chip': 'ذروة',
      'feature_solar_sync_title': 'مزامنة الطاقة الشمسية',
      'feature_solar_sync_subtitle': 'وازن الأحمال مع إنتاج الألواح الشمسية.',
      'feature_solar_sync_chip': 'شمس',
      'feature_green_tips_title': 'نصائح خضراء',
      'feature_green_tips_subtitle': 'استقبل نصائح بيئية للحفاظ على الاستهلاك.',
      'feature_green_tips_chip': 'خضراء',
      'feature_insights_digest_title': 'ملخص الرؤى',
      'feature_insights_digest_subtitle': 'ملخص أسبوعي يبرز أهم أحداث الطاقة والغرف.',
      'feature_insights_digest_chip': 'ملخص',
      'feature_scene_learning_title': 'تعلم المشاهد',
      'feature_scene_learning_subtitle': 'دع النظام يتعلم تعديلاتك اليدوية ويحسنها.',
      'feature_scene_learning_chip': 'تعلم',
      'feature_firmware_auto_title': 'تحديث تلقائي',
      'feature_firmware_auto_subtitle': 'حدّث البرامج الثابتة ليلًا لحماية الأجهزة.',
      'feature_firmware_auto_chip': 'تحديث',
      'feature_backup_restore_title': 'نسخ احتياطي واسترجاع',
      'feature_backup_restore_subtitle': 'انسخ تخطيطاتك احتياطيًا واستعدها بنقرة.',
      'feature_backup_restore_chip': 'نسخ',
      'feature_mfa_title': 'تسجيل ثنائي',
      'feature_mfa_subtitle': 'أضف تحققًا ثنائيًا للوصول عن بُعد.',
      'feature_mfa_chip': 'تحقق',
      'feature_privacy_mode_title': 'وضع الخصوصية',
      'feature_privacy_mode_subtitle': 'أوقف الميكروفونات والكاميرات بزر واحد.',
      'feature_privacy_mode_chip': 'خصوصية',
      'feature_shared_alerts_title': 'تنبيهات مشتركة',
      'feature_shared_alerts_subtitle': 'شارك التنبيهات الحرجة فورًا مع العائلة.',
      'feature_shared_alerts_chip': 'مشترك',
      'feature_automation_sandbox_title': 'مختبر الأتمتة',
      'feature_automation_sandbox_subtitle': 'جرّب الأتمتة المتقدمة قبل تطبيقها.',
      'feature_automation_sandbox_chip': 'مختبر',
      'feature_energy_budget_guard_title': 'حارس الميزانية',
      'feature_energy_budget_guard_subtitle': 'حدد ميزانية الطاقة وتلقَّ تنبيهات قبل التجاوز.',
      'feature_energy_budget_guard_chip': 'ميزانية',
      'feature_maintenance_scheduler_title': 'مجدول الصيانة',
      'feature_maintenance_scheduler_subtitle': 'تابع تغيير الفلاتر والمواعيد الدورية.',
      'feature_maintenance_scheduler_chip': 'صيانة',
    },
  };

  static Future<AppLocalizations> loadFromPrefs() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString(_prefKey) ?? 'en';
    return AppLocalizations(Locale(code));
  }

  Future<void> changeLocale(Locale locale) async {
    if (_locale == locale) return;
    _locale = locale;
    _strings = _localizedValues[_locale.languageCode] ?? _localizedValues['en']!;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, _locale.languageCode);
    notifyListeners();
  }
}
