import 'package:flutter/material.dart';

class EnhancementOption {
  const EnhancementOption({
    required this.id,
    required this.icon,
    required this.titleKey,
    required this.subtitleKey,
    required this.chipKey,
    this.defaultEnabled = false,
  });

  final String id;
  final IconData icon;
  final String titleKey;
  final String subtitleKey;
  final String chipKey;
  final bool defaultEnabled;
}

const enhancementCatalog = <EnhancementOption>[
  EnhancementOption(
    id: 'vacation_mode',
    icon: Icons.flight_takeoff,
    titleKey: 'feature_vacation_mode_title',
    subtitleKey: 'feature_vacation_mode_subtitle',
    chipKey: 'feature_vacation_mode_chip',
  ),
  EnhancementOption(
    id: 'night_lighting',
    icon: Icons.nightlight_round,
    titleKey: 'feature_night_lighting_title',
    subtitleKey: 'feature_night_lighting_subtitle',
    chipKey: 'feature_night_lighting_chip',
  ),
  EnhancementOption(
    id: 'energy_saver',
    icon: Icons.eco_outlined,
    titleKey: 'feature_energy_saver_title',
    subtitleKey: 'feature_energy_saver_subtitle',
    chipKey: 'feature_energy_saver_chip',
  ),
  EnhancementOption(
    id: 'auto_lock',
    icon: Icons.lock_clock,
    titleKey: 'feature_auto_lock_title',
    subtitleKey: 'feature_auto_lock_subtitle',
    chipKey: 'feature_auto_lock_chip',
  ),
  EnhancementOption(
    id: 'presence_simulation',
    icon: Icons.visibility_outlined,
    titleKey: 'feature_presence_simulation_title',
    subtitleKey: 'feature_presence_simulation_subtitle',
    chipKey: 'feature_presence_simulation_chip',
  ),
  EnhancementOption(
    id: 'air_quality_watch',
    icon: Icons.cloud_outlined,
    titleKey: 'feature_air_quality_watch_title',
    subtitleKey: 'feature_air_quality_watch_subtitle',
    chipKey: 'feature_air_quality_watch_chip',
  ),
  EnhancementOption(
    id: 'pet_monitor',
    icon: Icons.pets,
    titleKey: 'feature_pet_monitor_title',
    subtitleKey: 'feature_pet_monitor_subtitle',
    chipKey: 'feature_pet_monitor_chip',
  ),
  EnhancementOption(
    id: 'leak_alerts',
    icon: Icons.water_damage_outlined,
    titleKey: 'feature_leak_alerts_title',
    subtitleKey: 'feature_leak_alerts_subtitle',
    chipKey: 'feature_leak_alerts_chip',
  ),
  EnhancementOption(
    id: 'device_health',
    icon: Icons.stacked_bar_chart,
    titleKey: 'feature_device_health_title',
    subtitleKey: 'feature_device_health_subtitle',
    chipKey: 'feature_device_health_chip',
  ),
  EnhancementOption(
    id: 'battery_watch',
    icon: Icons.battery_full,
    titleKey: 'feature_battery_watch_title',
    subtitleKey: 'feature_battery_watch_subtitle',
    chipKey: 'feature_battery_watch_chip',
  ),
  EnhancementOption(
    id: 'security_patrol',
    icon: Icons.shield_moon,
    titleKey: 'feature_security_patrol_title',
    subtitleKey: 'feature_security_patrol_subtitle',
    chipKey: 'feature_security_patrol_chip',
  ),
  EnhancementOption(
    id: 'guest_pass',
    icon: Icons.badge_outlined,
    titleKey: 'feature_guest_pass_title',
    subtitleKey: 'feature_guest_pass_subtitle',
    chipKey: 'feature_guest_pass_chip',
  ),
  EnhancementOption(
    id: 'voice_assistant',
    icon: Icons.settings_voice,
    titleKey: 'feature_voice_assistant_title',
    subtitleKey: 'feature_voice_assistant_subtitle',
    chipKey: 'feature_voice_assistant_chip',
  ),
  EnhancementOption(
    id: 'geo_fencing',
    icon: Icons.gps_fixed,
    titleKey: 'feature_geo_fencing_title',
    subtitleKey: 'feature_geo_fencing_subtitle',
    chipKey: 'feature_geo_fencing_chip',
  ),
  EnhancementOption(
    id: 'cleaning_cycle',
    icon: Icons.cleaning_services,
    titleKey: 'feature_cleaning_cycle_title',
    subtitleKey: 'feature_cleaning_cycle_subtitle',
    chipKey: 'feature_cleaning_cycle_chip',
  ),
  EnhancementOption(
    id: 'smart_notifications',
    icon: Icons.notifications_active_outlined,
    titleKey: 'feature_smart_notifications_title',
    subtitleKey: 'feature_smart_notifications_subtitle',
    chipKey: 'feature_smart_notifications_chip',
  ),
  EnhancementOption(
    id: 'routine_suggestions',
    icon: Icons.auto_mode,
    titleKey: 'feature_routine_suggestions_title',
    subtitleKey: 'feature_routine_suggestions_subtitle',
    chipKey: 'feature_routine_suggestions_chip',
  ),
  EnhancementOption(
    id: 'peak_protection',
    icon: Icons.flash_on,
    titleKey: 'feature_peak_protection_title',
    subtitleKey: 'feature_peak_protection_subtitle',
    chipKey: 'feature_peak_protection_chip',
  ),
  EnhancementOption(
    id: 'solar_sync',
    icon: Icons.sunny,
    titleKey: 'feature_solar_sync_title',
    subtitleKey: 'feature_solar_sync_subtitle',
    chipKey: 'feature_solar_sync_chip',
  ),
  EnhancementOption(
    id: 'green_tips',
    icon: Icons.grass,
    titleKey: 'feature_green_tips_title',
    subtitleKey: 'feature_green_tips_subtitle',
    chipKey: 'feature_green_tips_chip',
  ),
  EnhancementOption(
    id: 'insights_digest',
    icon: Icons.article_outlined,
    titleKey: 'feature_insights_digest_title',
    subtitleKey: 'feature_insights_digest_subtitle',
    chipKey: 'feature_insights_digest_chip',
  ),
  EnhancementOption(
    id: 'scene_learning',
    icon: Icons.auto_awesome_motion,
    titleKey: 'feature_scene_learning_title',
    subtitleKey: 'feature_scene_learning_subtitle',
    chipKey: 'feature_scene_learning_chip',
  ),
  EnhancementOption(
    id: 'firmware_auto',
    icon: Icons.system_update_alt,
    titleKey: 'feature_firmware_auto_title',
    subtitleKey: 'feature_firmware_auto_subtitle',
    chipKey: 'feature_firmware_auto_chip',
  ),
  EnhancementOption(
    id: 'backup_restore',
    icon: Icons.backup_outlined,
    titleKey: 'feature_backup_restore_title',
    subtitleKey: 'feature_backup_restore_subtitle',
    chipKey: 'feature_backup_restore_chip',
  ),
  EnhancementOption(
    id: 'mfa',
    icon: Icons.verified_user_outlined,
    titleKey: 'feature_mfa_title',
    subtitleKey: 'feature_mfa_subtitle',
    chipKey: 'feature_mfa_chip',
  ),
  EnhancementOption(
    id: 'privacy_mode',
    icon: Icons.visibility_off_outlined,
    titleKey: 'feature_privacy_mode_title',
    subtitleKey: 'feature_privacy_mode_subtitle',
    chipKey: 'feature_privacy_mode_chip',
  ),
  EnhancementOption(
    id: 'shared_alerts',
    icon: Icons.family_restroom,
    titleKey: 'feature_shared_alerts_title',
    subtitleKey: 'feature_shared_alerts_subtitle',
    chipKey: 'feature_shared_alerts_chip',
  ),
  EnhancementOption(
    id: 'automation_sandbox',
    icon: Icons.science_outlined,
    titleKey: 'feature_automation_sandbox_title',
    subtitleKey: 'feature_automation_sandbox_subtitle',
    chipKey: 'feature_automation_sandbox_chip',
  ),
  EnhancementOption(
    id: 'energy_budget_guard',
    icon: Icons.account_balance_wallet_outlined,
    titleKey: 'feature_energy_budget_guard_title',
    subtitleKey: 'feature_energy_budget_guard_subtitle',
    chipKey: 'feature_energy_budget_guard_chip',
  ),
  EnhancementOption(
    id: 'maintenance_scheduler',
    icon: Icons.build_circle_outlined,
    titleKey: 'feature_maintenance_scheduler_title',
    subtitleKey: 'feature_maintenance_scheduler_subtitle',
    chipKey: 'feature_maintenance_scheduler_chip',
  ),
  EnhancementOption(
    id: 'scene_orchestrator',
    icon: Icons.auto_awesome_motion,
    titleKey: 'feature_scene_orchestrator_title',
    subtitleKey: 'feature_scene_orchestrator_subtitle',
    chipKey: 'feature_scene_orchestrator_chip',
  ),
  EnhancementOption(
    id: 'auto_shades',
    icon: Icons.blinds_closed,
    titleKey: 'feature_auto_shades_title',
    subtitleKey: 'feature_auto_shades_subtitle',
    chipKey: 'feature_auto_shades_chip',
  ),
  EnhancementOption(
    id: 'smart_irrigation',
    icon: Icons.grass,
    titleKey: 'feature_smart_irrigation_title',
    subtitleKey: 'feature_smart_irrigation_subtitle',
    chipKey: 'feature_smart_irrigation_chip',
  ),
  EnhancementOption(
    id: 'laundry_monitor',
    icon: Icons.local_laundry_service,
    titleKey: 'feature_laundry_monitor_title',
    subtitleKey: 'feature_laundry_monitor_subtitle',
    chipKey: 'feature_laundry_monitor_chip',
  ),
  EnhancementOption(
    id: 'sleep_routine',
    icon: Icons.bedtime,
    titleKey: 'feature_sleep_routine_title',
    subtitleKey: 'feature_sleep_routine_subtitle',
    chipKey: 'feature_sleep_routine_chip',
  ),
  EnhancementOption(
    id: 'wellness_dashboard',
    icon: Icons.favorite_outline,
    titleKey: 'feature_wellness_dashboard_title',
    subtitleKey: 'feature_wellness_dashboard_subtitle',
    chipKey: 'feature_wellness_dashboard_chip',
  ),
  EnhancementOption(
    id: 'fire_watch',
    icon: Icons.local_fire_department,
    titleKey: 'feature_fire_watch_title',
    subtitleKey: 'feature_fire_watch_subtitle',
    chipKey: 'feature_fire_watch_chip',
  ),
  EnhancementOption(
    id: 'air_purifier_sync',
    icon: Icons.air,
    titleKey: 'feature_air_purifier_sync_title',
    subtitleKey: 'feature_air_purifier_sync_subtitle',
    chipKey: 'feature_air_purifier_sync_chip',
  ),
  EnhancementOption(
    id: 'smart_panels',
    icon: Icons.space_dashboard,
    titleKey: 'feature_smart_panels_title',
    subtitleKey: 'feature_smart_panels_subtitle',
    chipKey: 'feature_smart_panels_chip',
  ),
  EnhancementOption(
    id: 'grid_alerts',
    icon: Icons.electric_bolt,
    titleKey: 'feature_grid_alerts_title',
    subtitleKey: 'feature_grid_alerts_subtitle',
    chipKey: 'feature_grid_alerts_chip',
  ),
  EnhancementOption(
    id: 'solar_forecast',
    icon: Icons.sunny_snowing,
    titleKey: 'feature_solar_forecast_title',
    subtitleKey: 'feature_solar_forecast_subtitle',
    chipKey: 'feature_solar_forecast_chip',
  ),
  EnhancementOption(
    id: 'power_sharing',
    icon: Icons.share_arrival_time,
    titleKey: 'feature_power_sharing_title',
    subtitleKey: 'feature_power_sharing_subtitle',
    chipKey: 'feature_power_sharing_chip',
  ),
  EnhancementOption(
    id: 'child_lockdown',
    icon: Icons.child_care,
    titleKey: 'feature_child_lockdown_title',
    subtitleKey: 'feature_child_lockdown_subtitle',
    chipKey: 'feature_child_lockdown_chip',
  ),
  EnhancementOption(
    id: 'garage_guard',
    icon: Icons.garage_outlined,
    titleKey: 'feature_garage_guard_title',
    subtitleKey: 'feature_garage_guard_subtitle',
    chipKey: 'feature_garage_guard_chip',
  ),
  EnhancementOption(
    id: 'ambient_music',
    icon: Icons.music_note,
    titleKey: 'feature_ambient_music_title',
    subtitleKey: 'feature_ambient_music_subtitle',
    chipKey: 'feature_ambient_music_chip',
  ),
  EnhancementOption(
    id: 'mood_lighting',
    icon: Icons.emoji_objects,
    titleKey: 'feature_mood_lighting_title',
    subtitleKey: 'feature_mood_lighting_subtitle',
    chipKey: 'feature_mood_lighting_chip',
  ),
  EnhancementOption(
    id: 'intelligent_cleaning',
    icon: Icons.vaccines,
    titleKey: 'feature_intelligent_cleaning_title',
    subtitleKey: 'feature_intelligent_cleaning_subtitle',
    chipKey: 'feature_intelligent_cleaning_chip',
  ),
  EnhancementOption(
    id: 'food_safety',
    icon: Icons.kitchen,
    titleKey: 'feature_food_safety_title',
    subtitleKey: 'feature_food_safety_subtitle',
    chipKey: 'feature_food_safety_chip',
  ),
  EnhancementOption(
    id: 'water_usage',
    icon: Icons.water,
    titleKey: 'feature_water_usage_title',
    subtitleKey: 'feature_water_usage_subtitle',
    chipKey: 'feature_water_usage_chip',
  ),
  EnhancementOption(
    id: 'doorbell_ai',
    icon: Icons.doorbell,
    titleKey: 'feature_doorbell_ai_title',
    subtitleKey: 'feature_doorbell_ai_subtitle',
    chipKey: 'feature_doorbell_ai_chip',
  ),
  EnhancementOption(
    id: 'smart_notifications',
    icon: Icons.notifications_active,
    titleKey: 'feature_smart_notifications_title',
    subtitleKey: 'feature_smart_notifications_subtitle',
    chipKey: 'feature_smart_notifications_chip',
  ),
  EnhancementOption(
    id: 'eco_challenge',
    icon: Icons.emoji_events_outlined,
    titleKey: 'feature_eco_challenge_title',
    subtitleKey: 'feature_eco_challenge_subtitle',
    chipKey: 'feature_eco_challenge_chip',
  ),
  EnhancementOption(
    id: 'climate_equalizer',
    icon: Icons.thermostat_auto,
    titleKey: 'feature_climate_equalizer_title',
    subtitleKey: 'feature_climate_equalizer_subtitle',
    chipKey: 'feature_climate_equalizer_chip',
  ),
  EnhancementOption(
    id: 'emergency_mode',
    icon: Icons.emergency_share,
    titleKey: 'feature_emergency_mode_title',
    subtitleKey: 'feature_emergency_mode_subtitle',
    chipKey: 'feature_emergency_mode_chip',
  ),
  EnhancementOption(
    id: 'storm_shield',
    icon: Icons.thunderstorm,
    titleKey: 'feature_storm_shield_title',
    subtitleKey: 'feature_storm_shield_subtitle',
    chipKey: 'feature_storm_shield_chip',
  ),
  EnhancementOption(
    id: 'smart_restock',
    icon: Icons.shopping_bag_outlined,
    titleKey: 'feature_smart_restock_title',
    subtitleKey: 'feature_smart_restock_subtitle',
    chipKey: 'feature_smart_restock_chip',
  ),
  EnhancementOption(
    id: 'wellbeing_coach',
    icon: Icons.self_improvement,
    titleKey: 'feature_wellbeing_coach_title',
    subtitleKey: 'feature_wellbeing_coach_subtitle',
    chipKey: 'feature_wellbeing_coach_chip',
  ),
  EnhancementOption(
    id: 'pet_feeder_sync',
    icon: Icons.set_meal,
    titleKey: 'feature_pet_feeder_sync_title',
    subtitleKey: 'feature_pet_feeder_sync_subtitle',
    chipKey: 'feature_pet_feeder_sync_chip',
  ),
  EnhancementOption(
    id: 'guest_dashboard',
    icon: Icons.groups_2,
    titleKey: 'feature_guest_dashboard_title',
    subtitleKey: 'feature_guest_dashboard_subtitle',
    chipKey: 'feature_guest_dashboard_chip',
  ),
  EnhancementOption(
    id: 'grid_failover',
    icon: Icons.power_outlined,
    titleKey: 'feature_grid_failover_title',
    subtitleKey: 'feature_grid_failover_subtitle',
    chipKey: 'feature_grid_failover_chip',
  ),
  EnhancementOption(
    id: 'comfort_insights',
    icon: Icons.insights,
    titleKey: 'feature_comfort_insights_title',
    subtitleKey: 'feature_comfort_insights_subtitle',
    chipKey: 'feature_comfort_insights_chip',
  ),
  EnhancementOption(
    id: 'adaptive_security',
    icon: Icons.security,
    titleKey: 'feature_adaptive_security_title',
    subtitleKey: 'feature_adaptive_security_subtitle',
    chipKey: 'feature_adaptive_security_chip',
  ),
  EnhancementOption(
    id: 'microclimate_zones',
    icon: Icons.deblur,
    titleKey: 'feature_microclimate_zones_title',
    subtitleKey: 'feature_microclimate_zones_subtitle',
    chipKey: 'feature_microclimate_zones_chip',
  ),
  EnhancementOption(
    id: 'calm_alerts',
    icon: Icons.notifications_paused,
    titleKey: 'feature_calm_alerts_title',
    subtitleKey: 'feature_calm_alerts_subtitle',
    chipKey: 'feature_calm_alerts_chip',
  ),
  EnhancementOption(
    id: 'dynamic_dashboard',
    icon: Icons.view_quilt,
    titleKey: 'feature_dynamic_dashboard_title',
    subtitleKey: 'feature_dynamic_dashboard_subtitle',
    chipKey: 'feature_dynamic_dashboard_chip',
  ),
  EnhancementOption(
    id: 'insight_timelines',
    icon: Icons.timeline,
    titleKey: 'feature_insight_timelines_title',
    subtitleKey: 'feature_insight_timelines_subtitle',
    chipKey: 'feature_insight_timelines_chip',
  ),
  EnhancementOption(
    id: 'performance_labs',
    icon: Icons.monitor_heart,
    titleKey: 'feature_performance_labs_title',
    subtitleKey: 'feature_performance_labs_subtitle',
    chipKey: 'feature_performance_labs_chip',
  ),
];
